POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "mehmet",
  "email": "ilkerqwd@gmail.com",
  "password": "123123123"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "ilker@gmail.com",
  "password": "123123123"
}