POST http://localhost:4000/api/posts
Content-Type: application/json

{
  "userId": "askdmqwkd",
  "desc": "anotherpost@gmail.com"
}

###

GET http://localhost:4000/api/posts/

###

GET http://localhost:4000/api/posts/61f7fa7c6346bd7d1a1547a2

###

PUT http://localhost:4000/api/posts/61f7fa7c6346bd7d1a1547a2
Content-Type: application/json

{
  "userId": "notfound",
  "desc": "tryingto@gmail.com",
  "img": "thisisimg.png"
}

###

DELETE http://localhost:4000/api/posts/61f7fa7c6346bd7d1a1547a2
Content-Type: application/json

{
  "userId": "notfound",
  "desc": "tryingto@gmail.com",
  "img": "thisisimg.png"
}
