POST http://localhost:4000/api/posts
Content-Type: application/json

{
  "userId": "askdmqwkd",
  "desc": "anotherpost@gmail.com"
}

###

GET http://localhost:4000/api/posts/

###

GET http://localhost:4000/api/posts/61f7fac2fcc17102731327d3

###

PUT http://localhost:4000/api/posts/61f7fac2fcc17102731327d3
Content-Type: application/json

{
  "userId": "askdmqwkd",
  "desc": "tryiddeditedngto@gmail.com",
  "img": "thisisimg.png"
}

###

DELETE http://localhost:4000/api/posts/61f7fa7c6346bd7d1a1547a2
Content-Type: application/json

{
  "userId": "notfound",
  "desc": "tryingto@gmail.com",
  "img": "thisisimg.png"
}



###

PUT http://localhost:4000/api/posts/61f7fac2fcc17102731327d3/like
Content-Type: application/json

{
    "userId": "askdmqwkd"
}

###

GET http://localhost:4000/api/posts/timeline/all
Content-Type: application/json

{
    "userId": "61f79c4cc388e4c85507375c"
}